platform :ios, '9.0'

target 'BUApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BUApp
  pod 'LCHereSDK', :path => '../', :inhibit_warnings => false

end


